train_dataset: mini-imagenet
train_dataset_args: { split: train }
tval_dataset: mini-imagenet
tval_dataset_args: { split: test }
val_dataset: mini-imagenet
val_dataset_args: { split: val }

model: meta-baseline
model_args:
  encoder: resnet12
  encoder_args: { }
load_encoder: ./save/classifier_mini-imagenet_resnet12/epoch-last.pth
n_way: 5
n_shot: 1
n_query: 15
train_batches: 200
ep_per_batch: 4

max_epoch: 100
optimizer: sgd
diffusion_optimizer: sgd
optimizer_args: { lr: 1.e-4, weight_decay: 5.e-4}
diffusion_optimizer_args: { lr: 1.e-3, weight_decay: 5.e-4, milestones: [30, 50, 80]}

visualize_datasets: True
overfit_lr: 0.000001
overfit_iterations: 10
loss_coff: 10.

save_epoch: 20

transformer:
  ema: true
  predict_xstart: true
  max_freq_log2: 14
  num_frequencies: 128
  n_embd: 512
  encoder_depth: 1
  decoder_depth: 1
  n_layer: 12
  n_head: 16
  dropout_prob: 0.1
  len_input: 3
  numstep: 10
  time: 100
