batch_size: 256
eval_fs_epoch: 5
fs_dataset: mini-imagenet
fs_dataset_args:
  split: test
max_epoch: 150
model: classifier
model_args:
  classifier: linear-classifier
  classifier_args:
    n_classes: 64
  encoder: resnet12
  encoder_args: {}
optimizer: sgd
optimizer_args:
  lr: 0.1
  milestones:
  - 90
  weight_decay: 0.0005
save_epoch: 5
train_dataset: mini-imagenet
train_dataset_args:
  augment: resize
  split: train
val_dataset: mini-imagenet
val_dataset_args:
  split: train_phase_val
visualize_datasets: true
